// <auto-generated />
using System;
using GamerJogoVelhaInfraData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamerJogoVelhaInfraData.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GamerJogoVelhaDomain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NameGame")
                        .IsRequired()
                        .HasColumnName("GameName")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("SiglaGame")
                        .IsRequired()
                        .HasColumnName("SiglaGame")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GamerJogoVelhaDomain.Entities.GameResult", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastGame")
                        .HasColumnType("datetime");

                    b.Property<long?>("Win")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("GamerJogoVelhaDomain.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NamePlayer")
                        .IsRequired()
                        .HasColumnName("NamePlayer")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("SiglaPlayer")
                        .IsRequired()
                        .HasColumnName("SiglaPlayer")
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GamerJogoVelhaDomain.Entities.GameResult", b =>
                {
                    b.HasOne("GamerJogoVelhaDomain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamerJogoVelhaDomain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
